### ISSUE TITLE
Could you please share the weight file?

### ISSUE THREAD

**Issue by lilong-wen** [fh2019ustc/DeepEraser#1]
Nice work, I'm very interested in your work, but I couldn't help but notice that you didn't upload the model's weight, could you please share the weight file so I can run the demo with more sophisticated masks?

**Comment by fh2019ustc** [comment]
Thanks for your attention to our work. We have already uploaded the weight:
![image](https://github.com/fh2019ustc/DeepEraser/assets/50725551/a7d4344d-b778-4394-a377-78d0a3b1ce20)

**Comment by lilong-wen** [comment]
Thanks for pointing out. I'm terribly sorry for my mistake.
